trigger:
- main  # Pipeline triggers on changes to the main branch

stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: BuildJob
    displayName: Build Job
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo " Building the application..."
    - script: echo " Build complete"

- stage: DeployToProd
  displayName: Deploy to Production
  dependsOn: Build
  jobs:
  - deployment: DeployProduction
    displayName: Production Deployment
    environment: production
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo " Deploying to Production Environment..."
